---
- name: install vim
  package:
    state: present
    name: vim

- name: create vim user config directories
  file:
    state: directory
    path: "{{ user_home_dir }}/{{ item }}"
    mode: 0700
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    seuser: system_u
  loop:
    - .vim/autoload
    - .vim/bundle

- name: push vimrc
  copy:
    src: "{{ role_path }}/files/vimrc"
    dest: "{{ user_home_dir }}/.vimrc"
    mode: 0400
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    setype: user_home_t
    seuser: system_u

- name: configure vim - pathogen
  get_url:
    url: "https://tpo.pe/pathogen.vim"
    dest: "{{ user_home_dir }}/.vim/autoload/pathogen.vim"
    mode: 0600
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    seuser: system_u

- name: add vim plugin - black
  git:
    repo: "https://github.com/psf/black.git"
    dest: "{{ user_home_dir }}/.vim/bundle/black"
    version: stable
    accept_hostkey: yes

- name: add vim plugin - code_complete
  git:
    repo: "https://github.com/mbbill/code_complete.git"
    dest: "{{ user_home_dir }}/.vim/bundle/vim-code-complete"
    accept_hostkey: yes

- name: add vim plugin - Dockerfile.vim
  git:
    repo: "https://github.com/ekalinin/Dockerfile.vim.git"
    dest: "{{ user_home_dir }}/.vim/bundle/vim-dockerfile"
    accept_hostkey: yes

- name: add vim plugin - salt-vim
  git:
    repo: "https://github.com/saltstack/salt-vim.git"
    dest: "{{ user_home_dir }}/.vim/bundle/salt-vim"
    accept_hostkey: yes

- name: add vim plugin - syntastic
  git:
    repo: "https://github.com/vim-syntastic/syntastic.git"
    dest: "{{ user_home_dir }}/.vim/bundle/vim-syntastic"
    accept_hostkey: yes

- name: add vim plugin - vim-airline
  git:
    repo: "https://github.com/vim-airline/vim-airline.git"
    dest: "{{ user_home_dir }}/.vim/bundle/vim-airline"
    accept_hostkey: yes

- name: add vim plugin - vim-closetag
  git:
    repo: "https://github.com/alvan/vim-closetag.git"
    dest: "{{ user_home_dir }}/.vim/bundle/vim-closetag"
    accept_hostkey: yes

- name: add vim plugin - vim-flake8
  git:
    repo: "https://github.com/nvie/vim-flake8.git"
    dest: "{{ user_home_dir }}/.vim/bundle/vim-flake8"
    accept_hostkey: yes

- name: add vim plugin - vim-jinja
  git:
    repo: "https://github.com/mitsuhiko/vim-jinja.git"
    dest: "{{ user_home_dir }}/.vim/bundle/vim-jinja"
    accept_hostkey: yes

- name: add vim plugin - vim-snippets
  git:
    repo: "https://github.com/honza/vim-snippets.git"
    dest: "{{ user_home_dir }}/.vim/bundle/vim-snippets"
    accept_hostkey: yes

- name: add vim plugin - vim-surround
  git:
    repo: "https://github.com/tpope/vim-surround.git"
    dest: "{{ user_home_dir }}/.vim/bundle/vim-surround"
    accept_hostkey: yes

- name: set owner/group on vim plugins to target user
  file:
    path: "{{ user_home_dir }}/.vim"
    state: directory
    recurse: yes
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    seuser: system_u
