#TODO Export files into Docker volume instead of /root/Music

FROM registry.fedoraproject.org/fedora:29
LABEL maintainer "Justin W. Flory <jflory7+dockerfile@gmail.com>"

WORKDIR /app
VOLUME /app
VOLUME /dev/cdrom

RUN dnf upgrade -y --refresh \
        && dnf install -y ripright \
        && dnf clean all

COPY ripright_entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["single"]
