---
- name: install openssh
  package:
    state: present
    name:
      - openssh
      - openssh-clients
      - openssh-server

- name: create user SSH config directory (~/.ssh/)
  file:
    state: directory
    path: "{{ user_home_dir }}/.ssh"
    mode: 0700
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    setype: ssh_home_t
    seuser: system_u

- name: push user SSH config (~/.ssh/config)
  copy:
    src: "{{ role_path }}/files/config"
    dest: "{{ user_home_dir }}/.ssh/config"
    mode: 0644
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    setype: ssh_home_t
    seuser: system_u

- name: create or update permissions on /etc/ssh/sshd_config.d/
  file:
    state: directory
    path: /etc/ssh/sshd_config.d/
    mode: 0700
    owner: root
    group: root
    setype: etc_t
    seuser: system_u

- name: push 01-system-owner-policy.conf (/etc/ssh/sshd_config.d/)
  template:
    src: 01-system-owner-policy.conf
    dest: /etc/ssh/sshd_config.d/01-system-owner-policy.conf
    mode: 0600
    owner: root
    group: root
    seuser: system_u
    setype: etc_t
  notify: restart sshd.service
