---
- name: gracefully clean up old RPM applications and reinstall as Flatpaks
  hosts: workstation
  become: yes

  vars:
    target_group: jflory
    target_user: jflory
    user_home_dir: /home/jflory

  tasks:
    - name: purge unused RPM repositories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/etc/yum.repos.d/bluejeans.repo"
        - "/etc/yum.repos.d/fedora-flash-plugin.repo"
        - "/etc/yum.repos.d/fedora-spotify.repo"

    - name: purge unused RPM packages
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - bluejeans
        - flash-plugin
        - google-talkplugin
        - protonmail-bridge
        - riot
        - spotify-client
        - spotify-curl
        - spotify-ffmpeg
        - zoom

    - name: reinstall most removed software as Flatpaks
      flatpak:
        name: "{{ item }}"
        state: present
        method: system
      loop:
        - ch.protonmail.protonmail-bridge
        - com.adobe.Flash-Player-Projector
        - com.bluejeans.BlueJeans
        - com.spotify.Client
        - im.riot.Riot
        - org.signal.Signal
        - us.zoom.Zoom
