= How to use jwflory/swiss-army

[link=https://creativecommons.org/licenses/by-sa/4.0/]
image::https://img.shields.io/badge/License-CC%20BY--SA%204.0-lightgrey.svg[License: CC BY-SA 4.0]

This doc explains how `jwflory/swiss-army` is used in practice.
It provides a baseline for how upstream uses this repo daily, should you https://github.com/jwflory/swiss-army/generate[use it as a template].


== Support matrix

The following distributions are currently "supported" (i.e. used) upstream:

* *Fedora*:
** Latest stable release
* *CentOS/RHEL*:
** 7.x
** 8.x


== How to provision a system

These are the quick commands to use for routine provisioning.
They could also be hooked up to a cronjob theoretically.

=== Fedora Workstation

[source,bash]
----
ansible-playbook -K -v playbooks/fedora-workstation.yml
----

=== RHEL/CentOS Workstation

[source,bash]
----
ansible-playbook -K -v playbooks/rhel-workstation.yml
----

=== CentOS Server (headless)

[source,bash]
----
ansible-playbook -K -v playbooks/centos-server.yml
----


== How to use this repository

This repository is a https://www.ansible.com/[Red Hat Ansible] configuration management project.
It includes Ansible Playbooks and Roles to set up RPM Linux distributions.
This section adds deeper context for how and why `jwflory/swiss-army` is used.

=== Roles

This repository categorizes two types of Roles:

* *`system`*:
  Installation and management of system-level / O.S.-specific software, packages, configurations, etc.
* *`apps`*:
  Standalone applications to use on any Linux distribution
  (_note_: in some cases, hard-coded defaults for RPM distributions are used)

=== Playbooks

*Playbooks* bring `system` and `apps` Roles together.
One playbook is written for each type of supported base system.
For example, upstream has three different playbooks for three different base systems:

[source,sh]
----
.
├── playbooks
│   ├── centos-server.yml
│   ├── fedora-workstation.yml
│   └── rhel-workstation.yml
----

Each base system *Playbook* is combined with a different combination of `system` and `apps` Roles.
Take a look at this Playbook for a RHEL/CentOS 8 Workstation:

[source,yaml]
----
---
- name: set up my preferred RHEL/CentOS 8 Workstation
  hosts: workstation
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    target_group: jwf
    target_user: jwf
    target_user_name: Justin W. Flory
    user_home_dir: /home/jwf

  roles:
    - { role: system/base, tags: ['base', 'system'] }
    - { role: system/rhel-workstation, tags: ['rhel', 'system'] }
    - { role: system/python, tags: ['python', 'system'] }
    - { role: apps/bash, tags: ['bash', 'terminal', 'apps'] }
    - { role: apps/git, tags: ['git', 'terminal', 'apps'] }
    - { role: apps/i3wm, tags: ['i3wm', 'desktop', 'apps'] }
    - { role: apps/npm, tags: ['npm', 'terminal', 'apps'] }
    - { role: apps/ssh, tags: ['ssh', 'terminal', 'apps'] }
    - { role: apps/tmux, tags: ['tmux', 'terminal', 'apps'] }
    - { role: apps/vim, tags: ['vim', 'terminal', 'apps'] }
----

Each *Playbook* is flexible for different combinations of `system` and `apps` Roles.
The multiple `tags` make it easier to build modular Playbooks by `--tags=` at run-time.


== How to configure your own `swiss-army`

To use `swiss-army` immediately, you likely need a RPM Linux distribution like https://getfedora.org/[Fedora] or https://www.centos.org/[CentOS].
Change the `inventory/inventory` file to match your specific environment.
(_Hint_: You can also use the `workstation` host in your Playbooks to always point to `127.0.0.1`.

If you run a Playbook as-is, you will have an RPM Linux distribution configured the way _I_ like it.
Obviously you can swap your own dotfiles with mine if you are bringing your own.
Or you can use mine as a base!
If you are really sure about that.
:wink:
