= How to make a bootable Linux USB key

[link=https://creativecommons.org/licenses/by-sa/4.0/]
image::https://img.shields.io/badge/License-CC%20BY--SA%204.0-lightgrey.svg[License: CC BY-SA 4.0]

This document explains how to create a bootable Linux USB key.
There are many methods to do this and many tools available to make this easier.
However, over time, these tools may change or break.
One tool that has not changed is `dd`.
Instead of searching my browser history each time I make a USB key, this is a more definitive guide for me to reference.


== Requirements

You need the following:

* Existing Linux or macOS system
* USB key (8GB minimum)
* https://gparted.org/[`gparted`]
* ISO image of your choice


== Use `gparted` to clear USB key

_Note_: This is only applicable to Linux systems.

Before creating a bootable USB key, make sure the USB key is cleared and unallocated.
In the past, I ran into weird issues when creating the bootable media before clearing the existing data.
Theoretically, it shouldn't be an issue, but technology is weird sometimes.

. Insert USB key into system.
. Open `gparted` as root (`sudo gparted`)
. Change partitioning scheme to `gpt`, wipe drive clean


== Download ISO image and check SHA sum

If provided, check the ISO image checksum against a provided checksum:

 echo "<sha512sum> <file name to check>" | sha512sum --check


== Create install media with `dd`

 sudo dd if=/path/to/image.iso of=/dev/sdX bs=128K conv=noerror,sync status=progress

From https://www.cyberciti.biz/faq/unix-linux-dd-create-make-disk-image-commands/[nixCraft]:

. *`if=/path/to/image.iso`*: Input device / ISO
. *`of=/dev/sdX`*: Output device
. *`bs=128K`*: Set block size to 128 KB (citation needed - _what does this really mean?_)
. *`conv=noerror`*: Tell dd to continue operation, ignoring all read errors
. *`sync`*: Add input blocks with zeroes if there were read errors, so data offsets stay in sync
. *`status=progress`*: See progress while making an image (requires GNU coreutils 8.24 or later)
