# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

eval $(ssh-agent)  # required for desktop ssh-agent to work as expected

export GOPATH=$HOME/wkspc/go
export PATH=$PATH:$HOME/.local/bin:$HOME/wkspc/bin:$GOPATH/bin:$HOME/.npm-global/bin
