# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

export CLASSPATH=.:$HOME/wkspc/bin/mysql-connector-java-5.1.39-bin.jar:$HOME/wkspc/bin/sqljdbc42.jar
export GOPATH=$HOME/wkspc/go
export JGRASP_HOME=/opt/jgrasp
export PATH=$PATH:$HOME/.local/bin:$HOME/wkspc/bin:$GOPATH/bin:$HOME/.npm-global/bin
